name: Export projects to HTML5 and deploy to GitHub Pages
on:
  push:
    branches:
      - develop

env:
  GODOT_VERSION: 3.4.2

jobs:
  export-html5:
    name: Export projects to HTML5 and deploy to GitHub Pages
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Export projects to HTML5
        run: |
          BASEDIR="$PWD"
          # Use absolute paths so that we can `cd` without having to go back to the parent directory manually.
          $BASEDIR
          ls -l
          #for demo in /; do
            # echo "$BASEDIR"
			      #ls 
            # "$BASEDIR"
            # echo "================================"
          #done
