name: "godot-ci export"
on:
  push:
    branches:
    - Godot-42-Stable

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: J4F-MiniShooterGame

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
           mkdir -v -p ~/.local/share/godot/export_templates/ 
           ls -Al /root/.local/share/godot/export_templates
           mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#          # Add SymLink
#          ln -s ~/.local/share/godot/export_templates ~/.local/share/godot/export_templates
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          #cd $EXPORT_NAME
          godot --headless --verbose --editor --quit-after 10
          godot --export-release --headless "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows
          path: build/windows

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
           ls -Al /root/.local/share/godot/export_templates
           mkdir -v -p ~/.local/share/godot/export_templates/ 
           mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#          ln -s ~/.local/share/godot/export_templates ~/.local/share/godot/export_templates
      - name: Web Build
        run: |
          mkdir -v -p build/web
          #cd $EXPORT_NAME
          godot --headless --verbose --editor --quit-after 10
          godot --export-release --headless "Web" build/web/index.html
          cp ./.github/dist/coi-serviceworker.min.js ./build/web/coi-serviceworker.min.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: web
          path: build/web
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # GITHUB_TOKEN: ${{ github.token }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.
